version: '3.8'
services:
    pingo.messages.db:
        image: postgres:17-alpine
        container_name: pingo-messages-db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: pingo_messages
        ports:
            - "5432:5432"
        volumes:
            - pingo_messages_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - pingo-network
    message.api:
        build:
            context: .
            dockerfile: Services/Message/Message.Api/Dockerfile
        container_name: message-api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:8080
            - ConnectionStrings__MessagesDb=Host=pingo.messages.db;Port=5432;Database=pingo_messages;Username=postgres;Password=postgres
        ports:
            - "5132:8080"
        depends_on:
            pingo.messages.db:
                condition: service_healthy
        networks:
            - pingo-network
    # --- Identity Service ---
    identity.api:
        image: identity.api
        build:
            context: .
            dockerfile: Identity/Dockerfile
        container_name: identity-api
        ports:
            - "8080:8080"
            - "8081:8081"
        environment:
            - ConnectionStrings__DefaultConnection=Host=identity.postgres;Database=identity_db;Username=postgres;Password=postgres
        depends_on:
            - identity.postgres
        networks:
            - pingo-network
    identity.postgres:
        image: postgres:15-alpine
        container_name: identity-postgres
        environment:
            - POSTGRES_DB=identity_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5433:5432" # Changed host port to 5433 to avoid conflict
        volumes:
            - identity_postgres_data:/var/lib/postgresql/data
        networks:
            - pingo-network
volumes:
    pingo_messages_data:
    identity_postgres_data:
networks:
    pingo-network:
        driver: bridge
